repos:  
  - repo: https://github.com/Azure4DevOps/check-azure-bicep
    rev: master
    hooks:
      - id: check-azure-bicep
      - id: check-azure-bicep-python
      - id: check-azure-bicep-format
      - id: check-azure-bicep-format-python
