repos:  
  - repo: https://github.com/Azure4DevOps/check-azure-bicep
    rev: v0.3.0
    hooks:
      - id: check-azure-bicep
 
  - repo: https://github.com/Azure4DevOps/check-azure-bicep
    rev: v0.3.0
    hooks:
      - id: check-azure-bicep-python
