
name: CI-Example

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"

jobs:
  build:
    runs-on: 'ubuntu-latest'        
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5.2.0
        with:      
          python-version: '3.10'
      - name: Run a multi-line script
        run: |          
          pip install --force-reinstall -v "azure-mgmt-rdbms==10.2.0b17"
          pip install pre-commit
          pre-commit --version
          pre-commit run --all-files

# pip install --force-reinstall -v "azure-mgmt-rdbms==10.2.0b17"
# temporary fix for dependecy https://github.com/Azure/azure-cli/issues/30102 
