name: CI-Example

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"

jobs:
  build:
    runs-on: 'ubuntu-latest'        
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.6.0
        with:      
          python-version: '3.10'
      - name: Run a multi-line script
        run: |
          pip install pre-commit
          pre-commit --version
          pre-commit run --all-files
